### PR TITLE
alt added to image overlay in js

### PR DESCRIPTION
**Pull request by afoketunji**
The alt tag is fine with the images (normal state) but when you click on the image and the overlay is displayed, the image doesn't have an alt tag. I've solved the issue now. Kindly check. Thanks.

### CODE REVIEW

**Comment by gitaarik** [comment]
I need this, why isn't this merged yet?

**Comment by lokesh** [comment]
@gitaarik this is being merged into ```master``` today. Sorry for delay.

**Comment by gitaarik** [comment]
Cool thanks!

**Comment by bearskin** [comment]
@lokesh The transfer of the alt-tag still seems (or maybe again) not to be working. Also on your homepage http://lokeshdhakar.com/projects/lightbox2/ the alt tag is not displayed correctly. There the alt-tag displays the src link.

**Pull request closed without merging**
