### PR TITLE
Add possibility to set translations.

### LINKED ISSUE #113: Add translation support for lightbox
This is my suggestion how to add language support for lightbox2, in my case I did these steps described below.
1. Make lightbox object available from code by adding lightbox object to window.

```
window.lightbox = new Lightbox options 
```
1. Lightbox options could look like this:

```
class LightboxOptions
  constructor: () ->
    @fadeDuration         = 500
    @fitImagesInViewport  = true 
    @resizeDuration       = 700
    @showImageNumberLabel = true
    @wrapAround           = false
    @translations         = {image: "Image", of: "of"} 

  # Change to localize to non-english language
  albumLabel: (curImageNum, albumSize) ->
    "#{@translations["image"]} #{curImageNum} #{@translations["of"]} #{albumSize}"
```
1. Add method setTranslations to Lightbox class

```
  setTranslations: (translations) ->
    @options.translations = translations
```
1. In code, forexample ruby, you can use it like

```
<script type="text/javascript">  
lightbox.setTranslations({image: "<%= t("public.common.lbox_image") %>", of: "<%= t("public.common.lbox_of") %>"} )
</script>
```

Hope this will help someone!

### PR DESCRIPTION
**Pull request by jaywink**
Exposes lightbox to the DOM and triggers an event when it is available. setTranslations method can be used to set language strings.

Implementation idea by github.com/ekaukis, closes #113

### CODE REVIEW

**Comment by sebslomski** [comment]
+1

**Comment by jaywink** [comment]
Anything I can add to this PR?

**Comment by reitermarkus** [comment]
I'm using your raw code at the moment, but somehow I can't get this to work. I haven't done anything with Javascript in a while, so the error might be on my end.

This is what I have:


    <script src="//raw.githubusercontent.com/jaywink/lightbox2/add-localization/js/lightbox.js"></script>
    <script>lightbox.setTranslations({image: "Bild", of: "von"})</script>


I hope you can help.

**Comment by elcodedocle** [comment]
+1!

**Comment by reitermarkus** [comment]
I found out that this is actually already implemented now and you can set it with the option [`albumLabel](https://github.com/lokesh/lightbox2/blob/1896b9e920591333c209566eaf7f462f73c064f3/dist/js/lightbox.js#L42)`.

I have this working:

    lightbox.option({
      'albumLabel': 'Bild %1 von %2'
    })

**Comment by jaywink** [comment]
@reitermarkus oh ok, closing this then, thanks for the heads up

**Pull request closed without merging**
